# Generated by Django 4.2.7 on 2025-06-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="acknowledgment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="complaint",
            name="building",
            field=models.CharField(
                blank=True,
                choices=[
                    ("main_station", "Main Station"),
                    ("platform", "Platform"),
                    ("office", "Office"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="contact_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="complaint",
            name="equipment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="floor_room",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="complaint",
            name="media_upload",
            field=models.FileField(blank=True, null=True, upload_to="complaint_media/"),
        ),
        migrations.AddField(
            model_name="complaint",
            name="nature_of_issue",
            field=models.CharField(
                blank=True,
                choices=[
                    ("non_functional", "Non-Functional"),
                    ("damaged", "Damaged"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="preferred_resolution_department",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="complaint",
            name="priority",
            field=models.CharField(
                choices=[("normal", "Normal"), ("high", "High"), ("urgent", "Urgent")],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="station",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="complaint",
            name="zone",
            field=models.CharField(
                blank=True,
                choices=[
                    ("northern", "Northern"),
                    ("southern", "Southern"),
                    ("eastern", "Eastern"),
                    ("western", "Western"),
                    ("central", "Central"),
                ],
                max_length=20,
            ),
        ),
    ]
