# Generated by Django 4.2.7 on 2025-06-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_complaint_acknowledgment_complaint_building_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("department", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("officer", "Officer"),
                            ("maintenance", "Maintenance Staff"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("address", models.TextField(blank=True)),
                ("qualifications", models.TextField(blank=True)),
                ("experience", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
