# Generated by Django 4.2.7 on 2025-07-02 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_registrationrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complaints",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
